CREATE TABLE PRODUCT
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME      VARCHAR(15)  NOT NULL,
    PRICE     INT          NOT NULL,
    IMAGE_URL VARCHAR(255) NOT NULL,
    HIDDEN    BOOLEAN      NOT NULL DEFAULT FALSE
);
