spring:
  application:
    name: spring-gift
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: ""

jwt:
  secret: kakaoTechCampus2025KNUFightingAzaAzaAza
  access-token-validity: 1800