spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

jwt:
  secret-key: ${SECRET_KEY:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d}
  access-token-validity: ${ACCESS_TOKEN_VALIDTY:3600000}
  refresh-token-validity: ${REFRESH_TOKEN_VALIDITY:604800000}
  issuer: ${ISSUER:http://auth.gift-app.com}

