CREATE TABLE product
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(255),
    price INT,
    image VARCHAR(255),
    mdApproved BOOLEAN DEFAULT FALSE
);

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    userid VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);