CREATE TABLE products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  image_url VARCHAR(500) NOT NULL
);

CREATE TABLE members (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE wishlist (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT,
  product_id BIGINT,
  amount INT
)