CREATE TYPE product_status AS ENUM ('APPROVED', 'PENDING', 'REJECTED');

CREATE TABLE products (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(15) NOT NULL,
    price INT NOT NULL,
    imageUrl VARCHAR(255) NOT NULL,
    status product_status NOT NULL
);

CREATE TABLE members (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(30) NOT NULL UNIQUE,
    password CHAR(60) NOT NULL
)